# Generated by Django 2.0 on 2017-12-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='text',
            field=models.TextField(default='Default Text.'),
            preserve_default=False,
        ),
    ]
