# Generated by Django 2.0 on 2017-12-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_entry_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=108)),
                ('attempt', models.TextField()),
                ('goal', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'code_entries',
            },
        ),
    ]
