# Generated by Django 2.0 on 2017-12-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_codeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeentry',
            name='explanation',
            field=models.TextField(default="The explanation for this entry hasn't been added yet."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codeentry',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
