# Generated by Django 2.0 on 2017-12-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_auto_20171216_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeentry',
            name='language',
            field=models.CharField(choices=[('JS', 'Javascript'), ('PYTHON', 'Python')], default='JS', max_length=50),
        ),
    ]
